### ISSUE TITLE
Update to v1.3.0 fails in TYPO3 v10.4

### ISSUE THREAD

**Issue by pipaltree** [xima-media/xima-typo3-mailcatcher#13]
When trying to update the extension to version 1.3.0 in TYPO3 v10.4 an exception is thrown stating:

> [ ParseError ]                                                                   
> syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)                                                                                   
>
> Exception trace:
> #0 ()
>   typo3conf/ext/xima_typo3_mailcatcher/Classes/Controller/BackendController.php:16

Maybe the problem occurs due to the added configuration in Services.yaml:
https://github.com/xima-media/xima-typo3-mailcatcher/commit/410a8210e04e209210ee2c090319ac5495d9267d#diff-d2a9a6effbda1d2c980f54b0f322f984996372c98b3af0577b8ec747d467735c

**Comment by maikschneider** [comment]
Damn. Yes, due to the now registered namespace in the Services.yaml the v11+ controller is loaded as well. 

We could try to remove the entry again. Or maybe better: Use Services.php to check the TYPO3 version to exclude the file.

Sorry. This extension needs automated tests.
