### ISSUE TITLE
Urls in catched mails are demaged

### ISSUE THREAD

**Issue by mediaessenz** [xima-media/xima-typo3-mailcatcher#17]
I would like to use this extension to catch mails on a staging system, which are generated by a registration process.
The generated mail contain a link to confirm a registration (double opt in).
Unfortunately the links in the mails are damaged and do not work as expected.

A working link should look like this:
https://domain/sign-in/registration/confirmation?tx_getaccess_confirmation%5Baction%5D=user&tx_getaccess_confirmation%5Bcontroller%5D=Confirmation&tx_getaccess_confirmation%5Bhash%5D=2720ba93a3007066&cHash=3179e61306999063853b2247a1bd4d

But in the catched mail inside of the backend module of this extension the same link look like this:
https://domain/sign-in/registration/confirmation?tx_getaccess_confirmation%5Baction%5D=user&tx_getaccess_confirmation%5Bcontroller%5D=Confirmation&tx_getaccess_confirmation%5Bhash%5D%2720ba93a3007066&cHash^3179e61306999063853b2247a1bd4d

As you can see, there are some small, but important differences:
The equal (=) sign after the hash value became a percentage (%) sign. And the equal (=) sign of the cHash become a ^ sign

Because of this, the registration process fails.

**Comment by maikschneider** [comment]
Hi @mediaessenz, thanks for reporting! I think I found the issue. Could you please test [v1.3.3](https://github.com/xima-media/xima-typo3-mailcatcher/releases/tag/v1.3.3)?
